"""Expand materials table with supplier and metadata

Revision ID: 32aeb9d7c0d7
Revises: 1b826b608eb9
Create Date: 2025-08-02 21:59:34.713281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32aeb9d7c0d7'
down_revision = '1b826b608eb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manufacturer_sku', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('supplier_url_1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('supplier_url_2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('supplier_url_3', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('tags')
        batch_op.drop_column('supplier_url_3')
        batch_op.drop_column('supplier_url_2')
        batch_op.drop_column('supplier_url_1')
        batch_op.drop_column('image_url')
        batch_op.drop_column('manufacturer_sku')

    # ### end Alembic commands ###
