"""Enhance transactions table with detailed logging fields

Revision ID: 6d2fc5e19850
Revises: e6551eff9576
Create Date: 2025-08-03 20:00:32.526445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d2fc5e19850'
down_revision = 'e6551eff9576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('initial_grams', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('final_grams', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))
        batch_op.alter_column('box_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('material_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('grams_withdrawn',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('grams_withdrawn',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('material_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('box_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('status')
        batch_op.drop_column('final_grams')
        batch_op.drop_column('initial_grams')
        batch_op.drop_column('transaction_type')

    # ### end Alembic commands ###
